Update cicd.yml
tweak 3

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -50,15 +50,19 @@ jobs:
         shell: powershell
         run: Start-Process -FilePath "docker" -ArgumentList "login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}" -Verb RunAs
 
-      - name: Verify Docker Hub Login
-        shell: powershell
-        run: |
-          if (-not (docker info | Select-String 'Username: ${{ secrets.DOCKER_USERNAME }}')) {
-            Write-Output "Docker login verification failed."
-            exit 1
-          } else {
-            Write-Output "Docker login verified."
-          }
+      - name: Docker Login
+        run: | 
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      # - name: Verify Docker Hub Login
+      #   shell: powershell
+      #   run: |
+      #     if (-not (docker info | Select-String 'Username: ${{ secrets.DOCKER_USERNAME }}')) {
+      #       Write-Output "Docker login verification failed."
+      #       exit 1
+      #     } else {
+      #       Write-Output "Docker login verified."
+      #     }
 
       - name: Build Docker Images
         shell: powershell
